services:
  whisper-hailo:
    image: whisper-hailo-image:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      IS_HAILO_ON_DEVICE: "FALSE"
      HAILO_VERSION: "VOSK"         # HAILO8, HAILO8L, or VOSK
      WHISPER_VARIANT: "base"         # base (default) or tiny
      VOSK_MODEL_PATH: "requirements_files/vosk-model-uk-v3-lgraph"   # path to VOSK model dir; used only when HAILO_VERSION=VOSK
      TTS_ENGINE_BINARY: "espeak-ng"
      TTS_DEFAULT_VOICE: "uk"
      TTS_DEFAULT_SPEED: "170"
    ports:
      - "10300:10300"                  # TCP  port for Wyoming Protocol
      - "54322:54322"                  # HTTP port for FastAPI
    volumes:
      - /dev:/dev
      - /lib/firmware:/lib/firmware
      - /lib/udev/rules.d:/lib/udev/rules.d
      - /lib/modules:/lib/modules 
    devices:
      - /dev/hailo0:/dev/hailo0
    command:
      - "poetry"
      - "run"
      - "uvicorn"
      - "main:app"
      - "--port"
      - "54322"
      - "--host"
      - "0.0.0.0"
      - "--log-config"
      - "infrastructure/config/logging_config.json"